name: adventuraexpeditions
favicon: null
layout_spectrum: 0.00052
typography_spectrum: 0.48694
title: adventura expeditions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#58676f'
    - '#cdb6b0'
    - '#e2e5e8'
    - '#258fb7'
    - '#000000'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.3714881206396967
purpose: []
